# Generated by Django 6.0.4 on 2026-04-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance_percentage',
            field=models.FloatField(default=0),
        ),
    ]
